### ISSUE TITLE
Feedback and feedforward

### ISSUE THREAD

**Issue by XDUSPONGE** [isapome/BrainProp#3]
Hello, thanks for your wonderful jod, and I have two questions
* The first is why does the last layer need the boltzmann controller instead of all using the maximum output 
* The second is that, in your paper, you say you use the feedback connection, while in the code, I did not see the feedback path clearly, it seems that you only use the transpose weight of the feedforward path 
Thanks for your reply

**Comment by isapome** [comment]
Hi, thank you for your interest. The Boltzmann controller is used for exploration (2% of the cases, while for the rest the max activity is selected) and the feedback is not implemented here because mathematically the update is supposed to be symmetrical to the feedforward updates.
